# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - stage: Analysis
    dependsOn: []
    jobs:
    - job:
      displayName: "Semgrep"
      pool:
        vmImage: ubuntu-latest
      steps:
      - script: |
          set -ex
          target_branch=origin/$(System.PullRequest.TargetBranch)
          files_changed=$(git --no-pager diff $target_branch..HEAD --name-only --diff-filter=d)
          python -m pip install --upgrade pip
          pip install semgrep
          semgrep --config "p/default" --error $files_changed
        displayName: 'Run Semgrep'

- stage: Build
  jobs:
  - job:
    displayName: "build"
    timeoutInMinutes: 60
    variables:
      DIFF_COVER_CHECK_THRESHOLD: 80
      DIFF_COVER_ENABLE: 'true'
    pool:
      vmImage: ubuntu-20.04

    container:
      image: sonicdev-microsoft.azurecr.io:443/sonic-slave-buster:latest

    steps:
    - checkout: self
      clean: true
      submodules: recursive
      displayName: 'Checkout code'
    - script: |
        set -x
        wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-5.0
        # Note: pytest-azurepipelines 1.0.3 requires new version of pytest (dist version 3.10.1), which will break pytest-cov 2.6.0
        sudo pip3 install pytest pytest-azurepipelines==0.8.0
        sudo pip3 install pytest-cov
      displayName: "Install build tools"
    - script: |
        set -ex

        python3 setup.py bdist_wheel
        mkdir -p $(Build.ArtifactStagingDirectory)/target/python-wheels
        cp dist/*.whl $(Build.ArtifactStagingDirectory)/target/python-wheels/
      displayName: "Build"
    - script: |
        set -ex

        sudo python3 -m pip install dist/swsssdk-2.0.1-py3-none-any.whl
        python3 -m pytest  --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml
      displayName: "Unit tests"
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: sonic-py-swsssdk
      displayName: "Archive artifacts"
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: Python 3
        failTaskOnFailedTests: true
      condition: succeededOrFailed()
      displayName: 'Publish Python 3 test results'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/**/*.coverage'
      displayName: 'Publish Python 3 test coverage'
